services:
  - type: web
    name: borneo-backend
    env: node
    buildCommand: npm install && npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
