name: Rollback

on:
  workflow_dispatch:
    inputs:
      target_commit:
        description: 'The commit hash to rollback to'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Perform Rollback
        env:
          TARGET_COMMIT: ${{ inputs.target_commit }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git read-tree -um HEAD $TARGET_COMMIT
          git commit -m "Rollback to commit $TARGET_COMMIT"
          git push origin HEAD:${{ github.ref_name }}
